# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('archivo_imagen', models.ImageField(upload_to='')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dorsales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dorsal', models.IntegerField()),
                ('archivo_imagen', models.ImageField(upload_to='')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorfotos.Competidor')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('archivo_imagen', models.ImageField(upload_to='')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('archivo_imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos_Dorsales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorfotos.Dorsales')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorfotos.Fotos')),
            ],
        ),
        migrations.AddField(
            model_name='dorsales',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorfotos.Eventos'),
        ),
    ]
