# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorfotos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dorsales',
            new_name='Dorsal',
        ),
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
        migrations.RenameModel(
            old_name='Fotos_Dorsales',
            new_name='Foto_dorsal',
        ),
    ]
