# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorfotos', '0002_auto_20161108_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competidor',
            name='archivo_imagen',
            field=models.ImageField(upload_to='imagenes/competidores'),
        ),
        migrations.AlterField(
            model_name='dorsal',
            name='archivo_imagen',
            field=models.ImageField(upload_to='imagenes/dorsal'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='archivo_imagen',
            field=models.ImageField(upload_to='imagenes/eventos'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='archivo_imagen',
            field=models.ImageField(upload_to='imagenes/fotos'),
        ),
    ]
