# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorfotos', '0003_auto_20161108_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competidor',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dorsal',
            name='archivo_imagen',
            field=models.ImageField(upload_to='imagenes/dorsales'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
