# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorfotos', '0004_auto_20161108_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto_dorsal',
            name='dorsal',
        ),
        migrations.RemoveField(
            model_name='foto_dorsal',
            name='foto',
        ),
        migrations.AddField(
            model_name='foto',
            name='dorsal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestorfotos.Dorsal'),
        ),
        migrations.AlterField(
            model_name='dorsal',
            name='competidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestorfotos.Competidor'),
        ),
        migrations.DeleteModel(
            name='Foto_dorsal',
        ),
    ]
