# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorfotos', '0005_auto_20161108_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='competidor',
            name='archivo_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='competidores'),
        ),
        migrations.AlterField(
            model_name='competidor',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dorsal',
            name='archivo_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='dorsales'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='archivo_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foto',
            name='archivo_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
